### ISSUE TITLE
Feature Request - Option to copy selected text in Integrated Terminal

### ISSUE THREAD

**Issue by vikas027** [dinhani/vscode-copy-on-select#1]
Thanks for this extension. Can you please take a feature request to copy selected text in Integrated Terminal as well? Thanks.

**Comment by dinhani** [comment]
I believe at the moment this is not possible through the extension because VSCode API has only mouse and keyboard events related to the editor area, but not for the terminal.

**Comment by dguendisch** [comment]
Seems this was added in the meantime: https://github.com/Microsoft/vscode/issues/36271

**Comment by dinhani** [comment]
Thanks for the info, @dieterguendisch . But now I believe this feature is not necessary in this extension because it became supported by VSCode by enabling the property `terminal.integrated.copyOnSelection`.
