### ISSUE TITLE
Didn't work in remote development mode

### ISSUE THREAD

**Issue by zhliuwenyu** [dinhani/vscode-copy-on-select#5]
already install in remote server plulgins, but never work;
should I change certain config or need bug fix

**Comment by jwercker** [comment]
Confirmed, doesn't work on WSL Ubuntu remote, please fix it, very useful extenstion.

**Comment by pzi123** [comment]
same here - in remove ssh mode does not work.

**Comment by dinhani** [comment]
Ok, how do I reproduce this issue? I have never used VSCode in remote mode.

**Comment by pzi123** [comment]
We use VScode to maintain AWS infrastructure with terraform and ansible and builds are run from the AWS jump host running redhat.  VScode is run from Windows/Mac with 'remote ssh' extension that allows to checkout the git code to the jump host, edit it there using VSCode, run builds and do git commit and push. See docs at https://github.com/microsoft/vscode-remote-release

**Comment by rbadapanda** [comment]
Instead of using clipboardy, using the following fixes the issue.

`
await vscode.env.clipboard.writeText(text);
`

I can create a PR if you want.

**Comment by dinhani** [comment]
Thanks everyone for the contribution. I published the version 0.0.7 that fixes this issue.
